import { buildPositionModel } from './positionModel.js';

const cases = [
  {
    name: 'Yellow risk reduce',
    input: {
      selectionScore: 84,
      selectionRank: 1,
      selectedNow: true,
      allocationScore: 90,
      allocationUsd: 100_000,
      livePnlUsd: -3_000,
      delta15mUsd: 300,
      delta1hUsd: -2_200,
      realizedPnlUsd: -274,
      burnQualityScore: 28,
      edgeScore: 43,
      edgeComplete: true,
    },
  },
  {
    name: 'Clear at -4k',
    input: {
      selectionScore: 84,
      selectionRank: 1,
      selectedNow: true,
      allocationScore: 90,
      allocationUsd: 100_000,
      livePnlUsd: -4_000,
      delta15mUsd: -3_000,
      delta1hUsd: -8_000,
      realizedPnlUsd: -1_000,
      burnQualityScore: 10,
      edgeScore: 15,
      edgeComplete: true,
    },
  },
  {
    name: 'Strong burn breakout',
    input: {
      selectionScore: 86,
      selectionRank: 2,
      selectedNow: true,
      allocationScore: 85,
      allocationUsd: 100_000,
      livePnlUsd: 10_000,
      delta15mUsd: 2_500,
      delta1hUsd: 7_500,
      realizedPnlUsd: 1_000,
      burnQualityScore: 82,
      edgeScore: 88,
      edgeComplete: true,
    },
  },
  {
    name: 'Live PnL +1500 first burn tier',
    input: {
      selectionScore: 86,
      selectionRank: 2,
      selectedNow: true,
      allocationScore: 85,
      allocationUsd: 100_000,
      livePnlUsd: 1_500,
      delta15mUsd: null,
      delta1hUsd: null,
      realizedPnlUsd: 0,
      burnQualityScore: 45,
      edgeScore: 45,
      edgeComplete: true,
    },
  },
  {
    name: 'Live PnL +3000 second burn tier',
    input: {
      selectionScore: 86,
      selectionRank: 2,
      selectedNow: true,
      allocationScore: 85,
      allocationUsd: 100_000,
      livePnlUsd: 3_000,
      delta15mUsd: null,
      delta1hUsd: null,
      realizedPnlUsd: 0,
      burnQualityScore: 55,
      edgeScore: 55,
      edgeComplete: true,
    },
  },
  {
    name: 'Same burn, S fundamentals',
    input: {
      selectionScore: 90,
      selectionRank: 1,
      selectedNow: true,
      allocationScore: 80,
      allocationUsd: 100_000,
      livePnlUsd: 5_000,
      delta15mUsd: 1_500,
      delta1hUsd: 3_000,
      realizedPnlUsd: 500,
      burnQualityScore: 75,
      edgeScore: 75,
      edgeComplete: true,
    },
  },
  {
    name: 'Same burn, B fundamentals',
    input: {
      selectionScore: 60,
      selectionRank: 10,
      selectedNow: true,
      allocationScore: 80,
      allocationUsd: 100_000,
      livePnlUsd: 5_000,
      delta15mUsd: 1_500,
      delta1hUsd: 3_000,
      realizedPnlUsd: 500,
      burnQualityScore: 75,
      edgeScore: 75,
      edgeComplete: true,
    },
  },
  {
    name: 'Unselected high alpha',
    input: {
      selectionScore: 82,
      selectionRank: 4,
      selectedNow: false,
    },
  },
  {
    name: 'Unselected top10 critical',
    input: {
      selectionScore: 71,
      selectionRank: 8,
      selectedNow: false,
    },
  },
] as const;

console.table(cases.map(({ name, input }) => {
  const result = buildPositionModel({
    ...input,
    maxAgentCapU: 200,
    minActionTargetU: 10,
    nowMs: Date.parse('2026-04-28T08:00:00Z'),
  });
  return {
    case: name,
    targetU: result.targetU,
    calendarPhase: result.calendarPhase,
    signalState: result.signalState,
    positionLayer: result.positionLayer,
    fundamentalRatio: result.metrics.fundamentalRatio,
    agentCapU: result.metrics.agentCapU,
    pnlAdjustment: result.metrics.pnlAdjustment ?? '-',
    confirmationPositionScore: result.metrics.confirmationPositionScore ?? '-',
    risk: result.metrics.riskState ? `${result.metrics.riskState} x${result.metrics.riskMultiplier}` : '-',
    burnProgress: result.metrics.burnProgress ?? '-',
    livePnlTargetRatio: result.metrics.livePnlTargetRatio ?? '-',
    realizedBonus: result.metrics.realizedQualityTargetBonus ?? '-',
  };
}));
